
server:
  port: 8090

spring:
  application:
    name: API-GATEWAY

  main:
    web-application-type: reactive

  config:
    import: optional:configserver:http://cloud-config-server-docker:8070/

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**







