spring:
  application:
    name: Config-test
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: capgemini
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
      
    show-sql: true 
    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
