spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/spring_project
    username: prithwi 
    password: capgemini
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://service-registry-docker:8085/eureka

      #http://service-registry-docker:8085/eureka
      #http://localhost:8085/eureka
